### PR TITLE
implemented logic for reservation and cancellation with Hashmap

### PR DESCRIPTION
**Pull request by Prasadpoojary**
Hi Veerala, 

I have contributed to this repo by adding hashmap for reservation tracking purpose. Please find the console output below and merge if everything looks good. 

```
Welcome to the Online Reservation System!
Enter your username: user1
Enter your password: password1
Login successful!

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 3
No reservation found for you.

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 1
Hey, user1... Please fill below details.
Reservation At : Bangalore
Reservation On ( YYYY-MM-DD ) : 2023-10-23
Reservation Successful


========================== Reservation Details ===============================
Reservation ID : 1
Reservation At : Bangalore
Reservation Date : Mon Oct 23 00:00:00 IST 2023
Reservation by : user1
==============================================================================

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 1
Hey, user1... Please fill below details.
Reservation At : Mangalore
Reservation On ( YYYY-MM-DD ) : October 23
Invalid Date format, date should be YYYY-MM-DD (2023-10-23)

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 1
Hey, user1... Please fill below details.
Reservation At : Mangalore
Reservation On ( YYYY-MM-DD ) : 2023-10-25
Reservation Successful


========================== Reservation Details ===============================
Reservation ID : 2
Reservation At : Mangalore
Reservation Date : Wed Oct 25 00:00:00 IST 2023
Reservation by : user1
==============================================================================

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 3


========================== Reservation Details ===============================
Reservation ID : 1
Reservation At : Bangalore
Reservation Date : Mon Oct 23 00:00:00 IST 2023
Reservation by : user1
==============================================================================


========================== Reservation Details ===============================
Reservation ID : 2
Reservation At : Mangalore
Reservation Date : Wed Oct 25 00:00:00 IST 2023
Reservation by : user1
==============================================================================

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 2
Enter the reservation ID to cancel : 2
Reservation Cancelled Successfully.


========================== Reservation Details ===============================
Reservation ID : 2
Reservation At : Mangalore
Reservation Date : Wed Oct 25 00:00:00 IST 2023
Reservation by : user1
==============================================================================

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 3


========================== Reservation Details ===============================
Reservation ID : 1
Reservation At : Bangalore
Reservation Date : Mon Oct 23 00:00:00 IST 2023
Reservation by : user1
==============================================================================

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 2
Enter the reservation ID to cancel : 10
Couldn't find your reservation for given Reservation ID : 10

Select an option:
1. Make a reservation
2. Cancel a reservation
3. Print my reservations
4. Exit
Enter your choice: 4
Thank you for using the Online Reservation System!

Process finished with exit code 0
```

Thanks,
Prasad, Coder

### CODE REVIEW

**Comment by Prasadpoojary** [comment]
Hi Veerala Rupa,

Merge this pull request if everything looks good. 

Thanks,
Prasad

**Comment by Rupa-Veerala** [comment]
> Hi Veerala Rupa,
> 
> Merge this pull request if everything looks good.
> 
> Thanks, Prasad

**Comment by Veerala-Rupa** [comment]
Thank you for your contributing

> > Hi Veerala Rupa,
> > Merge this pull request if everything looks good.
> > Thanks, Prasad

Thank you for your contributing

**Comment by Rupa-Veerala** [comment]
Respected sir,

Sorry to say, this repo is excluded from hacktoberfest2023.

Thanks,
Rupa.

**Pull request merged**
